- .github/workflows/github-actions.yml
> Ci: CI workflow 작성

- src/main/java/com/pomodoro/pomodoromate/auth/controllers/AuthController.java
- 로그아웃 API 구현
- RefreshToken 쿠키 삭제 및 만료
> Feat: 로그아웃 구현

- build.gradle
- src/main/java/com/pomodoro/pomodoromate/auth/controllers/AuthController.java
- src/main/java/com/pomodoro/pomodoromate/config/SwaggerConfig.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomController.java
- Swagger 적용
- springdoc-openapi 의존성 추가
- swagger config 설정
- 문서에 구현된 API 등록
> Docs: Swagger를 이용하여 API 문서 작성

- src/main/java/com/pomodoro/pomodoromate/auth/applications/IssueTokenService.java
- src/main/java/com/pomodoro/pomodoromate/auth/controllers/AuthController.java
- src/main/java/com/pomodoro/pomodoromate/auth/dtos/ReissuedTokenDto.java
- src/main/java/com/pomodoro/pomodoromate/auth/exceptions/RefreshTokenNotFound.java
- src/main/java/com/pomodoro/pomodoromate/auth/models/Token.java
- src/main/java/com/pomodoro/pomodoromate/auth/repositories/RefreshTokenRepository.java
- src/main/java/com/pomodoro/pomodoromate/config/SecurityConfig.java
- src/test/java/com/pomodoro/pomodoromate/auth/applications/IssueTokenServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/auth/controllers/AuthControllerTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomControllerTest.java
> Feat: 토큰 재발급 기능 구현

- src/main/java/com/pomodoro/pomodoromate/auth/applications/GuestLoginService.java
- src/main/java/com/pomodoro/pomodoromate/auth/controllers/AuthController.java
- src/main/java/com/pomodoro/pomodoromate/auth/dtos/CreateGuestRequest.java
- src/main/java/com/pomodoro/pomodoromate/auth/dtos/CreateGuestRequestDto.java
- src/main/java/com/pomodoro/pomodoromate/user/exceptions/InvalidUserNicknameException.java
- src/main/java/com/pomodoro/pomodoromate/user/models/User.java
- src/main/java/com/pomodoro/pomodoromate/user/models/UserInfo.java
- src/main/java/com/pomodoro/pomodoromate/user/policies/UserPolicy.java
- src/test/java/com/pomodoro/pomodoromate/auth/applications/GuestLoginServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/auth/controllers/AuthControllerTest.java
- 게스트 로그인 시 닉네임 설정하도록 변경
- 게스트 로그인 API Body에 nickname 추가
- 게스트 User 생성 시 nickname도 설정하도록 변경
> Chore: 게스트 로그인 시 닉네임 설정하도록 변경

- src/main/java/com/pomodoro/pomodoromate/common/dtos/PageDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomsService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomController.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomSummariesDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomSummaryDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomsServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomControllerTest.java
> Feat: 스터디룸 목록 조회 구현

- src/main/java/com/pomodoro/pomodoromate/auth/applications/GuestLoginService.java
- src/main/java/com/pomodoro/pomodoromate/auth/exceptions/UnauthorizedException.java
- src/main/java/com/pomodoro/pomodoromate/config/SecurityConfig.java
- src/main/java/com/pomodoro/pomodoromate/participant/applications/ParticipateService.java
- src/main/java/com/pomodoro/pomodoromate/participant/cotrollers/ParticipantController.java
- src/main/java/com/pomodoro/pomodoromate/participant/models/Participant.java
- src/main/java/com/pomodoro/pomodoromate/participant/models/ParticipantId.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepository.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/exceptions/StudyRoomNotFoundException.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoomId.java
- src/main/java/com/pomodoro/pomodoromate/user/models/User.java
- src/main/java/com/pomodoro/pomodoromate/user/models/UserId.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/ParticipateServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/participant/cotrollers/ParticipantControllerTest.java
> Feat: 스터디 참가 구현

- build.gradle
- src/main/java/com/pomodoro/pomodoromate/config/QueryDslConfig.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepository.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryImpl.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryQueryDsl.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomController.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomDetailDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomSummaryDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomControllerTest.java
- 스터디룸 조회 API 구현
- QueryDsl 의존성 추가
> Feat: 스터디룸 조회 구현

- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomsService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomSummaryDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/repositories/StudyRoomRepository.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/repositories/StudyRoomRepositoryImpl.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/repositories/StudyRoomRepositoryQueryDsl.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomsServiceTest.java
- 스터디룸 목록 조회 응답 데이터 추가
- 스터디 설명, 참가자 수 추가
- 참가자 수를 추가하기 위해 쿼리 추가
> Chore: 스터디룸 목록 조회 응답 데이터 변경

- Dockerfile
- Docker Image 최적화(사이즈 568MB -> 163MB)
- dockerfile 수정
- 베이스 이미지 변경
- Multi Stage
- alpine에 추가
> Perf: Docker Image 최적화

- src/main/java/com/pomodoro/pomodoromate/common/dtos/PageDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomsService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomController.java
- src/main/java/com/pomodoro/pomodoromate/user/applications/ValidateUserService.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomsServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomControllerTest.java
- src/test/java/com/pomodoro/pomodoromate/user/applications/ValidateUserServiceTest.java
- 스터디룸 관련 API에 유저 validate 기능 추가
- 스터디룸 조회
- 스터디룸 목록 조회
- 스터디룸 생성
> Chore: 스터디룸 관련 API에 유저 validate 기능 추가

- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomServiceTest.java
- 스터디룸 생성 시, 생성자를 참가자로 추가하도록 변경
> Chore: 스터디룸 생성 시, 생성자를 참가자로 추가하도록 변경

- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomDetailDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- 스터디룸 조회 시, 타이머 시간 설정을 위해 studyRoom updateAt도 가져오도록 변경
> Chore: 스터디룸 조회 시, studyRoom updateAt도 가져오도록 변경

- src/main/java/com/pomodoro/pomodoromate/config/SwaggerConfig.java
> Feat: Swagger Config에 JWT 헤더 추가

- src/main/java/com/pomodoro/pomodoromate/auth/utils/JwtUtil.java
- src/main/java/com/pomodoro/pomodoromate/common/models/EntityId.java
- src/main/java/com/pomodoro/pomodoromate/participant/applications/LeaveStudyService.java
- src/main/java/com/pomodoro/pomodoromate/participant/applications/ParticipateService.java
- src/main/java/com/pomodoro/pomodoromate/participant/dtos/ParticipantSummaryDto.java
- src/main/java/com/pomodoro/pomodoromate/participant/models/Participant.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryImpl.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryQueryDsl.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/StudyProgressService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomDetailDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomSummaryDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/main/java/com/pomodoro/pomodoromate/user/applications/ValidateUserService.java
- src/test/java/com/pomodoro/pomodoromate/auth/applications/GuestLoginServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/LeaveStudyServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/ParticipateServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/StudyProgressServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/user/applications/ValidateUserServiceTest.java
- 스터디룸 조회 API에 참가자 조회 추가
- 참가자가 생성될 때, 사용자의 UserInfo도 가지고 있도록 변경
> Feat: 스터디룸 조회 API에 참가자 조회 추가

- src/main/java/com/pomodoro/pomodoromate/participant/applications/LeaveStudyService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CompleteStudyRoomService.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/LeaveStudyServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/CompleteStudyRoomServiceTest.java
- 스터디룸에 참여자가 없으면 방이 자동으로 삭제되는 기능 추가
- CompleteStudyRoomService를 생성하여 방 삭제 기능 분리
> Feat: 스터디룸에서 모든 참여자가 나가면 방 삭제 기능 추가

- src/main/java/com/pomodoro/pomodoromate/participant/applications/ParticipateService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/exceptions/InvalidMaxParticipantCountException.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/exceptions/MaxParticipantExceededException.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/MaxParticipantCount.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/ParticipateServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoomTest.java
- 스터디룸에 최대 참가자 수가 초과되지 않도록 유효성 검사 구현
- 최대 참가자 수를 초과하는지 확인하는 메서드를 스터디룸 모델에 추가
- 유효성 검사가 예상대로 작동하는지 확인하기 위해 단위 테스트 추가
> Feat: 스터디룸 최대 참가자 수 제한 추가

- src/main/java/com/pomodoro/pomodoromate/participant/applications/ParticipateService.java
- src/main/java/com/pomodoro/pomodoromate/participant/cotrollers/ParticipantController.java
- src/main/java/com/pomodoro/pomodoromate/participant/models/Participant.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepository.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryImpl.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryQueryDsl.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomController.java
- src/main/java/com/pomodoro/pomodoromate/user/models/UserInfo.java
- src/main/java/com/pomodoro/pomodoromate/websocket/WebSocketEventListener.java
- src/main/java/com/pomodoro/pomodoromate/websocket/WebSocketHandler.java
- WebSocket 연결이 종료될 때, 다른 참가자에게 알림을 보내는 기능 추가
- WebSocketEventListener 클래스에 handleWebSocketDisconnectListener 메서드를 구현하여 해당 기능을 처리
- 참가자가 모두 나갔을 경우 해당 스터디룸을 완료하는 기능도 함께 구현
> Feat: 웹소켓 연결 종료 시, 다른 참가자에게 알리는 기능 추가

- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomController.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/CreateStudyRoomRequest.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/CreateStudyRoomRequestDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/NextStepStudyRoomDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/StudyRoomDetailDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/TimeSetDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/exceptions/InvalidTimeRangeException.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/Step.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/TimeSet.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/policies/StudyRoomPolicy.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/StudyProgressServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomControllerTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoomTest.java
- StudyRoom 엔티티에 스텝별 TimeSet 추가
- 스터디룸 조회 시, 설정 시간 조회하도록 변경
- 스터디룸 생성 시, 시간설정 기능 추가
> Feat: 타이머 시간설정 기능 추가

- src/main/java/com/pomodoro/pomodoromate/auth/config/JwtConfig.java
- src/main/java/com/pomodoro/pomodoromate/auth/utils/JwtUtil.java
- src/main/java/com/pomodoro/pomodoromate/common/utils/HttpUtil.java
- src/main/java/com/pomodoro/pomodoromate/config/WebMvcConfig.java
- src/test/java/com/pomodoro/pomodoromate/auth/applications/IssueTokenServiceTest.java
- dev 서버와 prod 서버 각각의 설정값을 나타내기 위해 @Value 어노테이션을 사용함
> Chore: @Value 어노테이션을 사용하여 dev와 prod 서버의 설정값을 구분하여 추가

- src/main/java/com/pomodoro/pomodoromate/auth/controllers/AuthController.java
- src/main/java/com/pomodoro/pomodoromate/auth/filters/JwtAuthenticationFilter.java
- src/main/java/com/pomodoro/pomodoromate/common/utils/HttpUtil.java
- src/main/java/com/pomodoro/pomodoromate/config/HttpConfig.java
- same site 변수 httpConfig로 이동
- 필터 예외 메시지에 인코딩 코드 추가
> Chore: same site 변수 httpConfig로 이동

- src/main/java/com/pomodoro/pomodoromate/config/SwaggerConfig.java
운영 환경에서 임시적으로 스웨거를 사용할 수 있도록 배포 서버 URL 추가
> Chore: 스웨거에 서버 URL 추가

- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/EditStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomController.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/EditStudyRoomRequest.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/dtos/EditStudyRoomRequestDto.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/EditStudyRoomServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/controllers/StudyRoomControllerTest.java
> Feat: 스터디룸 정보 수정 기능 구현

- src/main/java/com/pomodoro/pomodoromate/auth/applications/GoogleLoginService.java
- src/main/java/com/pomodoro/pomodoromate/auth/config/GoogleConfig.java
- src/main/java/com/pomodoro/pomodoromate/participant/applications/ParticipateService.java
- src/main/java/com/pomodoro/pomodoromate/participant/exceptions/ForbiddenStudyHostActionException.java
- src/main/java/com/pomodoro/pomodoromate/participant/models/Participant.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/EditStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/StudyProgressService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/repositories/StudyRoomRepository.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/ParticipateServiceIntegrationTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/EditStudyRoomServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/StudyProgressServiceTest.java
- 스터디방 생성시 방장 권한 부여
- 방장만이 스터디방 설정을 변경할 수 있도록 수정
- 방장만이 스터디 다음 단계로 넘길 수 있도록 수정
> Feat: 방장 역할 및 권한 추가 

- src/main/java/com/pomodoro/pomodoromate/participant/applications/GetParticipantsService.java
- src/main/java/com/pomodoro/pomodoromate/participant/applications/LeaveStudyService.java
- src/main/java/com/pomodoro/pomodoromate/participant/applications/ParticipateService.java
- src/main/java/com/pomodoro/pomodoromate/participant/cotrollers/ParticipantController.java
- src/main/java/com/pomodoro/pomodoromate/participant/dtos/ParticipantSummaryDto.java
- src/main/java/com/pomodoro/pomodoromate/participant/models/Participant.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryImpl.java
- src/main/java/com/pomodoro/pomodoromate/participant/repositories/ParticipantRepositoryQueryDsl.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/CreateStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/applications/StudyRoomHostService.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/exceptions/HostExistsException.java
- src/main/java/com/pomodoro/pomodoromate/studyRoom/models/StudyRoom.java
- src/main/java/com/pomodoro/pomodoromate/websocket/WebSocketEventListener.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/LeaveStudyServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/ParticipateServiceIntegrationTest.java
- src/test/java/com/pomodoro/pomodoromate/participant/applications/ParticipateServiceTest.java
- src/test/java/com/pomodoro/pomodoromate/studyRoom/applications/GetStudyRoomServiceTest.java
- 방장이 스터디룸을 나갔을때 다음으로 들어온 참가자에게 자동으로 방장이 넘어가는 기능 추가
- 방장을 부여할때 유효성 검사 추가
- Participant에게 참가 시간을 추가
- StudyRoomHostService 추가
> Feat: 방장 자동 넘기기 기능 추가
